Vagrant.configure("2") do |config|

	config.vm.define "selhandaS" do |server|
	  server.vm.box = "debian/bookworm64"
	  server.vm.hostname = "selhandaS"
	  server.vm.network "private_network", ip: "192.168.56.110"
	  server.vm.provider "virtualbox" do |vb|
		vb.memory = 2048
		vb.cpus = 3
	  end
	  server.vm.provision "file", source: './confs', destination: "~/confs"
	  server.vm.provision "shell", path: "scripts/setup_server.sh"
	end
end
