Vagrant.configure("2") do |config|

  config.vm.define "selhandaS" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "selhandaS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/setup_server.sh"
  end


  config.vm.define "selhandaSW" do |worker|
    worker.vm.box = "debian/bookworm64"
    worker.vm.hostname = "selhandaSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/setup_worker.sh"
  end
end

