apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-1
  labels:
    app: web-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-1
  template:
    metadata:
      labels:
        app: web-app-1
    spec:
      containers:
      - name: web-app-1
        image: paulbouwer/hello-kubernetes:1
        ports:
        - containerPort: 8888
        env:
        - name: MESSAGE
          value: "Hello from App 1!"
