apiVersion: v1
kind: Service
metadata:
  name: web-app-1-service
spec:
  selector:
    app: web-app-1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3030
  type: ClusterIP
